### ISSUE TITLE
as a user I should be able to evaluate a picture with a simple binary choice

### ISSUE THREAD

**Issue by daymos** [CYPIAPT-LNDSE/Face-It#1]

**Comment by SimonJStewart** [comment]
Will it be possible to have multiple examples to show by friday e.g.
Face 1 -  "is this happy or sad" 
Face 2 - "is this Happy or Angry"?

I think this would be good to have when presenting the prototype

**Comment by daymos** [comment]
By Friday there will be a playable version of the game. Im working now on creating 2 sets of 5 questions each. Does that answer the question ?

**Comment by SimonJStewart** [comment]
If the binary choices offered in those questions are not all the same then yes.

**Comment by daymos** [comment]
yes, we have 4 emotions in place for now
