### ISSUE TITLE
do you have suggestions for the app name?

### ISSUE THREAD

**Issue by daymos** [CYPIAPT-LNDSE/Face-It#10]

**Comment by daymos** [comment]
we will propose something by the end of the sprint in any case

**Comment by SimonJStewart** [comment]
No particular name in mind, I'll ask some potential users for suggestions

**Comment by ghost** [comment]
We discussed the name this morning, and proposed "Face It" as a temporary name. Obviously, we can change at any point, but we wanted to give it a name for our own design process.
