### ISSUE TITLE
design level page

### ISSUE THREAD

**Issue by daymos** [CYPIAPT-LNDSE/Face-It#102]
[https://gm1.ggpht.com/njl2PpXiURs0s1G3kXmyGiSOOQAhQYMLl-31562LMHek9l7M2qxz5mwLeSxyJS2VtUpAbJ5badlrexDVpXn_l4RhyV1HlTB1jBdSwHLv5UhB4bqx-uuY5hO1l1QvO0mzpwKQFidKB5gJLJmQDGsLXgSB2Yb4GwoWpBjF7k7zN1tFdi-W7Whn1qZVb7r5GPTUrue5eHfjyjKCZj1ytO-Yb0xDV64PflELFLjbWaY-2hyRnnw6iD6OpFaPkIoTQ-qHPOwaXrUthRQjxxhzl2i_iwNIKD8h2Z87MykaH-_Jfr00qBU443K2r3PXNufwlXAOodnRw_utJjPMxiwlYvXCx_x3K_qRy087V0OM9vr6OST1wRyABvA3re6Z9prsJ36MpM-3trJPAABRFkflbSKQJsT6pppw5MRnfZp2EVVwoTqSgFOO_ZiSjNO9baN4v3Cw6rdgQnMBRTKZXp-RxhOOJ0KOmwTNDVIUgT80PMraQ0ilsqNPLh6ZxYd6VwtucklmHYsalmmVFhAdlxysyR7SJnOvRukCbiRPFvHFq3v7PAug2Ay-rzR6vySjpNRmHrTR98Gn963buX7GCUFdmtckzxgAxUgEM1qjmKGWEXspto7ajSd3bhYhe-S-dnfxYbELNcmwGCeZS7Wtsk5LHkP7n0xMcC0-JFAV8QfMkqe213KkPVCnTnoOUHdxxyNyhwbfqOGgC3Z4eZDQUw=w3044-h2596-l75-ft](url)

**Comment by RichAWarren** [comment]
Link doesnt work?

**Comment by daymos** [comment]
sorry, just copy paste it into url box

**Comment by daymos** [comment]
btw this starts monday

**Comment by helau64** [comment]
Closed by #112
