### ISSUE TITLE
Move into AFC organisation repo

### ISSUE THREAD

**Issue by CYPIAPT-admin** [CYPIAPT-LNDSE/Face-It#11]
Organization link - https://github.com/CYPIAPT-LNDSE

**Comment by daymos** [comment]
I need admin right for the CYPIPT organisation to do the transfer

**Comment by CYPIAPT-admin** [comment]
admin rights have been granted

**Comment by sofer** [comment]
@daymos you might have missed this one.

**Comment by daymos** [comment]
thanks @sofer.
@CYPIAPT-admin, I just tried and I get this error: `You don't have admin rights to CYPIAPT-LNDSE.`

**Comment by CYPIAPT-admin** [comment]
Hi @daymos I've resent the invitation to become an admin

**Comment by daymos** [comment]
Hello @CYPIAPT-admin thank you, done.
