### ISSUE TITLE
users need to be able to access the level page whenever they want

### ISSUE THREAD

**Issue by helau64** [CYPIAPT-LNDSE/Face-It#128]

**Comment by matthewiiv** [comment]
What other pages does the level page need to be accessible from? As it stands now it can be reached from the lifetime results page and round results page, although the button that links there is labelled 'Play'.
Do you think this should be renamed since it doesn't lead directly into the game

**Comment by helau64** [comment]
Okay, great – when I opened this issue, pressing play on either page took you straight back into another round of the game, without going through the level page. Wasn't aware that had been changed.

**Comment by helau64** [comment]
From a UX standpoint, I think it would make sense to have the button on round results take you right back into another game round and stay labelled play. Definitely a good idea to rename the button wherever it's taking you to the level page though.
