### ISSUE TITLE
Bugs in emotion graphs in lifetime results

### ISSUE THREAD

**Issue by helau64** [CYPIAPT-LNDSE/Face-It#129]
- Styling not coming through
- Path not visible
- Too wide on iPhone 5
- Only happiness, sadness and surprise are showing

**Comment by matthewiiv** [comment]
Could you let me know how to recreate these bugs / post screenshots

**Comment by helau64** [comment]
Sorry, just put this here last week as notes to myself so I didn't properly bug test – gonna close this issue and re-add bugs individually as I find them
