### ISSUE TITLE
Presentation/Demo

### ISSUE THREAD

**Issue by CYPIAPT-admin** [CYPIAPT-LNDSE/Face-It#133]
Hi all,

There was a hope to show off Face-It on Friday at an event, is this going to be possible/Do you have a link to a previous version we could use? We're also submitting a funding application on Tuesday, and were wondering if it would be stable by then/could we keep a stable version up while developing.

**Comment by daymos** [comment]
Hi there,

That sounds great!

Regarding the video, I have been in touch with Simon this week,  the app is almost ready, and he knows we'll send something to be used in the video today. 

Regarding it being stable, could you clarify what you mean? If you mean ready for production (i.e release for the public to use it), usually development for mobile apps goes on for months so I don't think we could be ready by Tuesday. We can be faster than that, but we don't want to deliver a substandard product. 

If you want to have something to show, I can upload the demo we did after the 4 days sprint online in the browser so you'll have something to show. Let me know if this is what you need and I will be able to do it later today. And as soon as the current version under development is ready we can replace it. 

Would that be all right for you?

**Comment by daymos** [comment]
@CYPIAPT-admin there is a online version of the app here: `https://cypiapt-lndse.github.io/Face-It/`
I've added this link at the top of the readme. 
Please don't use this for testing. It will be ready for testing next week.
Also we don't have validation yet, so use only lowercase characters for the userid.
