### ISSUE TITLE
Lifetime result node spread

### ISSUE THREAD

**Issue by matthewiiv** [CYPIAPT-LNDSE/Face-It#140]
Lifetime results nodes are spread based on the time between rounds. This means they can cluster if multiple rounds are completed in quick succession or be spread far apart if some time is left between them.

![selection_022](https://cloud.githubusercontent.com/assets/8082570/19692669/aa623812-9ad0-11e6-9e27-ebd2728a0234.png)

**Comment by matthewiiv** [comment]
Should we treat each round as a node with even spacing between nodes, or group nodes by day?

**Comment by helau64** [comment]
I've been having a look at how other apps deal with this, looks like the general approach in cases like ours (where the user is likely to be playing lots of rounds in quick succession) is having one node per day

**Comment by matthewiiv** [comment]
I have implemented it as average result per day.
