### ISSUE TITLE
Opening screen appears to be misaligned on Android

### ISSUE THREAD

**Issue by sofer** [CYPIAPT-LNDSE/Face-It#173]
To be specific, it's a OnePlus 1.

![screenshot_2016-11-03-14-35-07](https://cloud.githubusercontent.com/assets/37059/19970187/2b3417d6-a1d3-11e6-9613-6f5a5bdda557.png)

Perhaps *Play*, *Lifetime results* and *Logout* could all be made visible without scrolling.

**Comment by daymos** [comment]
@heatherlauren  we had noticed this on some devices I recon. Shall we do this tomorrow when we work on the safari issue?

**Comment by helau64** [comment]
Haven't been able to test in fully, but I believe this should probably already be fixed in my open pull request

**Comment by sofer** [comment]
Appears to be fixed. 👍
