### ISSUE TITLE
As a user I should be able to progress through a level system

### ISSUE THREAD

**Issue by daymos** [CYPIAPT-LNDSE/Face-It#2]

**Comment by daymos** [comment]
level system will likely not be in place for at the end of this sprint

**Comment by SimonJStewart** [comment]
Will there be a screen that we can show that would indicate there will be a narrative / level structure to follow?

**Comment by SimonJStewart** [comment]
Will there be a screen that we can show that would indicate there will be a narrative / level structure to follow?

**Comment by daymos** [comment]
If you think that will add something to the app we could do it. I would suggest to leave that to the next sprint entirely, since whatever  we make now in regard to this feature, we will have to redo from scratch once we properly set up a login system/database. So we could spend that time making what we are at now really cool.

**Comment by SimonJStewart** [comment]
Ok leave it for this sprint then, only adds as a visual for presentation purposes, better to go with functionality

**Comment by daymos** [comment]
ok
