### ISSUE TITLE
general design question

### ISSUE THREAD

**Issue by daymos** [CYPIAPT-LNDSE/Face-It#49]
We have done some research on designing for autistic people, and tried to implement those in the app. As a result the app looks different form most apps. We are not experts on designing for these specific users but we are happy with the current result. Just wanted to get a feedback on that from you. You can see some screenshots in the wiki

**Comment by SimonJStewart** [comment]
Looks great :) Clean and clear!

**Comment by daymos** [comment]
thanks!
