### ISSUE TITLE
a set or several sets of images will be included into the application ( opposed to having the images uploaded by the users temselves)

### ISSUE THREAD

**Issue by daymos** [CYPIAPT-LNDSE/Face-It#6]

**Comment by daymos** [comment]
simon, not sure if we discussed this thoroughly yesterday, but I would suggest to have a set of images included in the app to run the game. So we will not allow the users to upoad iamges. What do you think?

**Comment by SimonJStewart** [comment]
Yes for MVP we will only use images within the application.
It is expected in later levels of the game that the user will take photos of themselves or others for the purpose of the game.

i.e. user is instructed to "take a photo of yourself / your friend looking happy" and then told whether they have received a suitable rating of it.

**Comment by daymos** [comment]
ok cool.
