### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by CYPIAPT-admin** [CYPIAPT-LNDSE/Face-It#94]
- Add in details on tech used
- Add in details to run locally

**Comment by daymos** [comment]
@CYPIAPT-admin i've updated the readme. Can you tell me how much details do you want in terms of tech used?

**Comment by CYPIAPT-admin** [comment]
@daymos Sorry, I somehow missed this. The App stack and installation details look good. I think this is good for now, so will close
