### ISSUE TITLE
Case study

### ISSUE THREAD

**Issue by sofer** [CYPIAPT-LNDSE/Face-It#95]
We need:
- Project name
- The client: 
- Challenge:
- Solution: 
- The one-week prototype:
- The four-week MVP: 
- Technology used:

We need a very short version for now. We can do something longer when the project is completed.

**Comment by daymos** [comment]
@sofer 
- Project name: Face it
- The client: simon stewart - anna freud
- Challenge: Train autistic children to recognize emotions on people's faces. 
- Solution: mobile app game. Kids can guess the emotions of certain faces and keep track of their progress over time. A level system encourages engagement over time.
- The one-week prototype: Researched designing for autistic people and developed a suitable design according to those guidelines. Developed the whole core functionalities of the game, provided the customer an online version of it and an android app that was sent around for testing via email.
- The four-week MVP: Massive refactor, provide robustness to the whole app, add proper database. Acting on the feedback from actual users we are adding some features to the core game flow, setting up real level system, phone number based login system. Implementing the features that were just stubbed for the prototype, namely dashboard with progress over time of users and some data comparison.  Automated tools ( uploader ) to create game set of different difficulty, with pictures provided by the users.  Release on android and iOS market.
- Technology used: 
  For the prototype: serverless architecture, jquery, boostrap, sass, cordova.
  For the mvp: still a serverless architecture , PWA app, jquery, handlebars, pouchDB, couchDB, cordova.
